# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        file_source.storage:
            adapter: 'asyncaws'
            options:
                client: 'app.services.remote_storage.client'
                bucket: '%env(REMOTE_STORAGE_FILE_SOURCE_BUCKET)%'

        git_repository.storage:
            adapter: 'local'
            options:
                directory: '%git_repository_store_directory%'

        serialized_suite.storage:
            adapter: 'asyncaws'
            options:
                client: 'app.services.remote_storage.client'
                bucket: '%env(REMOTE_STORAGE_SERIALIZED_SUITE_BUCKET)%'
