# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        file_source.storage:
            adapter: 'local'
            options:
                directory: '%file_source_store_directory%'

        run_source.storage:
            adapter: 'local'
            options:
                directory: '%run_source_store_directory%'

        git_repository.storage:
            adapter: 'local'
            options:
                directory: '%git_repository_store_directory%'
