security:
    enable_authenticator_manager: true
    providers:
        user_provider:
            id: SmartAssert\UsersSecurityBundle\Security\UserProvider
    firewalls:
        main:
            pattern:  '^/'
            stateless: true
            custom_authenticators:
                - SmartAssert\UsersSecurityBundle\Security\Authenticator
            provider: user_provider
            entry_point: SmartAssert\UsersSecurityBundle\Security\AuthenticationEntryPoint

    access_control:
        - { path: '^/', roles: ROLE_USER }
