parameters:
    fixtures_base_path: '%env(resolve:FIXTURES_BASE_PATH)%'
    test_authentication_provider_bundle_frontend_token_provider_users:
        'user1@example.com': 'password'
        'user2@example.com': 'password'
    test_authentication_provider_bundle_users_url: 'http://localhost:9080'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Services\EntityRemover:
        public: true

    App\Tests\Services\FileStoreFixtureCreator:
        public: true
        arguments:
            $fixturesReader: '@test_fixtures.storage'

    App\Tests\Services\DirectoryLister:
        public: true

    SmartAssert\SymfonyTestClient\SymfonyClient:
        public: true

    app.tests.integration.http.client:
        public: true
        class: GuzzleHttp\Client
        arguments:
            $config:
                base_uri: "https://localhost/"
                verify: false

    SmartAssert\SymfonyTestClient\HttpClient:
        arguments:
            $httpClient: '@app.tests.integration.http.client'

    GuzzleHttp\Psr7\HttpFactory:

    Psr\Http\Message\RequestFactoryInterface:
        alias: GuzzleHttp\Psr7\HttpFactory

    Psr\Http\Message\ResponseFactoryInterface:
        alias: GuzzleHttp\Psr7\HttpFactory

    Psr\Http\Message\ServerRequestFactoryInterface:
        alias: GuzzleHttp\Psr7\HttpFactory

    Psr\Http\Message\StreamFactoryInterface:
        alias: GuzzleHttp\Psr7\HttpFactory

    Psr\Http\Message\UploadedFileFactoryInterface:
        alias: GuzzleHttp\Psr7\HttpFactory

    Psr\Http\Message\UriFactoryInterface:
        alias: GuzzleHttp\Psr7\HttpFactory

    Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface:
        class: Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory

    App\Tests\Services\ResponseAsserter:
        public: true

    App\Services\SuiteSerializer:
        public: true
        arguments:
            $serializedSuiteReader: '@serialized_suite.storage'
            $serializedSuiteWriter: '@serialized_suite.storage'
