parameters:
    fixtures_base_path: '%env(resolve:FIXTURES_BASE_PATH)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    webignition\HttpHistoryContainer\Container:
        public: true

    App\Tests\Services\EntityRemover:
        public: true

    App\Tests\Services\FileStoreFixtureCreator:
        public: true
        arguments:
            $fixturesReader: '@test_fixtures.storage'

    App\Tests\Services\AuthenticationConfiguration:
        public: true
        arguments:
            $validToken: '%env(VALID_AUTHENTICATION_TOKEN)%'
            $invalidToken: '%env(INVALID_AUTHENTICATION_TOKEN)%'
            $headerName: !php/const SmartAssert\UsersSecurityBundle\Security\AuthorizationProperties::DEFAULT_HEADER_NAME
            $headerValuePrefix: !php/const SmartAssert\UsersSecurityBundle\Security\AuthorizationProperties::DEFAULT_VALUE_PREFIX
            $authenticatedUserId: '%env(AUTHENTICATED_USER_ID)%'

    App\Tests\Services\AuthorizationRequestAsserter:
        public: true
        arguments:
            $usersSecurityBundleBaseUrl: '%users_security_bundle_base_url%'

    App\Tests\Services\DirectoryLister:
        public: true

    App\Tests\Services\Application\Routes:
        arguments:
            $addFileUrl: '/{{ sourceId }}/{{ filename }}'
            $removeFileUrl: '/{{ sourceId }}/{{ filename }}'
            $createSourceUrl: '/'
            $listSourcesUrl: '/list'
            $getSourceUrl: '/{{ sourceId }}'
            $updateSourceUrl: '/{{ sourceId }}'
            $deleteSourceUrl: '/{{ sourceId }}'
            $prepareSourceUrl: '/{{ sourceId }}/prepare'
            $readSourceUrl: '/{{ sourceId }}/read'

    App\Tests\Services\Application\SymfonyClient:

    app.tests.integration.http.client:
        public: true
        class: GuzzleHttp\Client
        arguments:
            $config:
                base_uri: "https://localhost/"
                verify: false

    App\Tests\Services\Application\HttpClient:
        arguments:
            $httpClient: '@app.tests.integration.http.client'

    app.tests.services.application.functional:
        public: true
        class: App\Tests\Services\Application\Application
        arguments:
            $client: '@App\Tests\Services\Application\SymfonyClient'

    app.tests.services.application.integration:
        public: true
        class: App\Tests\Services\Application\Application
        arguments:
            $client: '@App\Tests\Services\Application\HttpClient'

    GuzzleHttp\Psr7\HttpFactory:

    Psr\Http\Message\RequestFactoryInterface:
        alias: GuzzleHttp\Psr7\HttpFactory

    Psr\Http\Message\ResponseFactoryInterface:
        alias: GuzzleHttp\Psr7\HttpFactory

    Psr\Http\Message\ServerRequestFactoryInterface:
        alias: GuzzleHttp\Psr7\HttpFactory

    Psr\Http\Message\StreamFactoryInterface:
        alias: GuzzleHttp\Psr7\HttpFactory

    Psr\Http\Message\UploadedFileFactoryInterface:
        alias: GuzzleHttp\Psr7\HttpFactory

    Psr\Http\Message\UriFactoryInterface:
        alias: GuzzleHttp\Psr7\HttpFactory

    Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface:
        class: Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory
