parameters:
    fixtures_base_path: '%env(resolve:FIXTURES_BASE_PATH)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    webignition\HttpHistoryContainer\Container:
        public: true

    App\Tests\Services\EntityRemover:
        public: true

    App\Tests\Services\FileStoreFixtureCreator:
        public: true
        arguments:
            $fixturesReader: '@test_fixtures.storage'

    App\Tests\Services\ApplicationClient:
        public: true

    App\Tests\Services\AuthenticationConfiguration:
        public: true
        arguments:
            $valid: '%env(VALID_AUTHENTICATION_TOKEN)%'
            $invalid: '%env(INVALID_AUTHENTICATION_TOKEN)%'

    App\Tests\Services\AuthorizationRequestAsserter:
        public: true
        arguments:
            $usersSecurityBundleBaseUrl: '%users_security_bundle_base_url%'

    App\Tests\Services\DirectoryLister:
        public: true
