services:
    _defaults:
        autowire: true
        autoconfigure: true

    webignition\HttpHistoryContainer\Container:
        public: true

    GuzzleHttp\Handler\MockHandler:
        public: true
        class: GuzzleHttp\Handler\MockHandler

    GuzzleHttp\HandlerStack:
        public: true
        class: GuzzleHttp\HandlerStack
        factory: ['GuzzleHttp\HandlerStack', 'create']
        arguments:
            $handler: '@GuzzleHttp\Handler\MockHandler'

    App\Tests\Services\Source\SourceRemover:
        public: true

    App\Services\FileStoreFactory:
        public: true
        arguments:
            $basePath: '%file_store_base_path%'

    App\Services\DirectoryDuplicator:
        public: true
