parameters:
    source_fixtures_path: '%env(resolve:SOURCE_FIXTURES_PATH)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    webignition\HttpHistoryContainer\Container:
        public: true

    GuzzleHttp\Handler\MockHandler:
        public: true
        class: GuzzleHttp\Handler\MockHandler

    GuzzleHttp\HandlerStack:
        public: true
        class: GuzzleHttp\HandlerStack
        factory: ['GuzzleHttp\HandlerStack', 'create']
        arguments:
            $handler: '@GuzzleHttp\Handler\MockHandler'

    App\Tests\Services\EntityRemover:
        public: true

    App\Services\Source\Finder:
        public: true

    App\Tests\Services\FileStoreFixtureCreator:
        public: true
        arguments:
            $sourceFixturesPath: '%source_fixtures_path%'
            $fileStoreBasePath: '%file_store_base_path%'

    App\Services\FileStoreManager:
        public: true
        arguments:
            $basePath: '@app.configuration.file_store_base_path'

    App\Services\GitRepositoryCheckoutHandler:
        public: true

    App\Services\UserGitRepositoryPreparer:
        public: true

    App\Services\RunSourcePreparer:
        public: true
